version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip3 install -r requirements.txt
  build:
    commands:
      - python -m pytest --junitxml=.reports/report.xml
reports:
  pytest_reports:
    files:
      - report.xml
    base-directory: .reports
    file-format: JUNITXML
artifacts:
  files:
    - '**/*'